image: 'appirio/dx:beta'
stages:
  - quality_scan
  - deploy
  - validate
sonarqube_scan:
  stage: quality_scan
  script:
    - >-
      sonar-scanner-ee -Dsonar.login=$SONAR_LOGIN -Dsonar.qualitygate.wait=true
      -Dsonar.qualitygate.timeout=300
  only:
    - QA_donotrun
    - UAT
validate_against_QA:
  stage: validate
  cache: &ref_0
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node
  except: &ref_1
    - schedules
  script:
    - >-
      adx deploy:source --sourcepath
      force-app/main/default --testlevel NoTestRun
      --checkonly --targetalias QA
  only:
    - /^featureQA/.*/

validate_against_QA:
  stage: validate
  cache: &ref_0
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node
  except: &ref_1
    - schedules
  script:
    - >-
      adx deploy:source --sourcepath
      force-app/main/default --testlevel NoTestRun
      --checkonly --targetalias TEMPQA
  only:
    - 
validate_against_TEMPQA:
  stage: validate
  cache: &ref_0
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node
  except: &ref_1
    - schedules
  script:
    - >-
      adx deploy:source --sourcepath
      force-app/main/default --testlevel NoTestRun
      --checkonly --targetalias TEMPQA
  only:
    - TEMPQA
deploy_to_QA:
  stage: deploy
  cache: *ref_0
  except: *ref_1
  script:
    - >-
      adx deploy:source --sourcepath
      force-app/main/default
      --targetalias QA
  only:
    - QA
validate_against_PROD:
  stage: validate
  cache: *ref_0
  except: *ref_1
  script:
    - >-
      adx deploy:source --sourcepath
      force-app/main/default
      --checkonly --targetalias PROD
  only:
    - /^validate/.*/
deploy_to_PROD:
  stage: deploy
  cache: *ref_0
  except: *ref_1
  script:
    - >-
      adx deploy:source --sourcepath
      force-app/main/default --testlevel RunLocalTests
      --targetalias PROD
  only:
    - master
