image: 'appirio/dx:beta'
stages:
  - cleanup
  - quality_scan
  - deploy
  - validate
  - merge_request
sonarqube_scan:
  stage: quality_scan
  script:
    - >-
      sonar-scanner-ee -Dsonar.login=$SONAR_LOGIN -Dsonar.qualitygate.wait=true
      -Dsonar.qualitygate.timeout=300
  except:
    - tags
    - schedules
sonarqube_merge_request_scan:
  stage: quality_scan
  script:
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - >-
      sonar-scanner-ee -Dsonar.login=$SONAR_LOGIN -Dsonar.qualitygate.wait=true
      -Dsonar.qualitygate.timeout=300
  only:
    - merge_requests
cleanup:
  stage: cleanup
  variables:
    GIT_STRATEGY: clone
  script:
    - 'adx ci:shell --script cleanUp.sh --arguments master'
  only:
    - schedules
validate_against_QA:
  stage: validate
  cache: &ref_0
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node
  except: &ref_1
    - schedules
  script:
    - >-
      adx deploy:source --sourcepath
      force-app/main/default --testlevel NoTestRun
      --checkonly --targetalias QA
  only:
    - /^featureQA/.*/
deploy_to_QA:
  stage: deploy
  cache: *ref_0
  except: *ref_1
  script:
    - >-
      adx deploy:source --sourcepath
      force-app/main/default
      --targetalias QA
  only:
    - QA
validate_against_PROD:
  stage: validate
  cache: *ref_0
  except: *ref_1
  script:
    - >-
      adx deploy:source --sourcepath
      force-app/main/default
      --checkonly --targetalias PROD
  only:
    - /^validate/.*/
deploy_to_PROD:
  stage: deploy
  cache: *ref_0
  except: *ref_1
  script:
    - >-
      adx deploy:source --sourcepath
      force-app/main/default --testlevel RunLocalTests
      --targetalias PROD
  only:
    - master
