/*
*******************************************************************************************************
* (C) Copyright 2020 Yokogawa. All rights reserved.
* This code is property of Yokogawa. Use, duplication and
* disclosure in any form without permission of copyright holder is prohibited.
* 
******************************************************************************************************* 
* @author Chitrakishore
* @version 1.0
* @created 13/07/2020
* @description 
* This class is used to write the methods for API related call.
*
* @test class name - YG_ProductRegistrationControllerTest
*
*  Change History:
*  MM/DD/YYYY			Developer Name			Comments
*  
*  
*
*/


public class YG_Constants {
    
    public static final String CL_CODE_SUCCESS = '0000';
   
    /* Cyberlibrary API ERROR CODE [starts here] */    
    public static final String CL_ERR_CODE_SEARCH_NOT_FOUND = '0001';
    public static final String CL_ERR_CODE_DOC_NOT_FOUND = '0002';
    public static final String CL_ERR_CODE_SEARCH_OVERFLOW = '0003';
    /*public static final String CL_ERR_CODE_SEARCH_NOT_FOUND = '0004';
    public static final String CL_ERR_CODE_SEARCH_NOT_FOUND = '0001';
    public static final String CL_ERR_CODE_SEARCH_NOT_FOUND = '0001';
    public static final String CL_ERR_CODE_SEARCH_NOT_FOUND = '0001';*/
    
    public static final String DOCUMENT_OUTPUT_ITEM = '1,2,3,4,5,6,7,8,10';
    public static final String CERTIFICATE_OUTPUT_ITEM = '1,2,3,4,5,6,7,8,9,10,11,12,13,14';
    public static final String FILE_EXTENSION = 'PDF';
    public static final String FILE_TYPE = 'Document';
    
    public static final String GENERAL_SPECIFICATION = 'General Specifications';
    public static final String INSTRUCTION_MANUAL  = 'Instruction Manuals';
    public static final String TECHNICAL_INFORMATION = 'Technical Information';
    public static final String DRAWING = 'Drawings';
    public static final String CERTIFICATE = 'Certificates';
    public static final String X_CLA_Message = 'Normal';
    
    public static String message='Test';

}